# Generated by Django 3.0.6 on 2020-05-29 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100)),
                ('cat_description', models.TextField(blank=True)),
                ('cat_img', models.ImageField(upload_to='category_img')),
                ('cat_parent', models.ForeignKey(blank=True, limit_choices_to={'cat_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.Product')),
                ('alts', models.ManyToManyField(related_name='alternative_products', to='product.Product')),
            ],
            options={
                'verbose_name': 'Alternative',
                'verbose_name_plural': 'Alternatives',
            },
        ),
    ]
