# Generated by Django 3.0.6 on 2020-05-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_product', to='product.Product')),
                ('accessories', models.ManyToManyField(related_name='accessories_products', to='product.Product')),
            ],
            options={
                'verbose_name': 'Accessories',
                'verbose_name_plural': 'Accessoriess',
            },
        ),
    ]
